### ISSUE TITLE
I run your code, appear such error: " 2019-07-18 07:44:12.064168: F tensorflow/stream_executor/cuda/cuda_dnn.cc:189] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream"

### ISSUE THREAD

**Issue by bignwei1029** [xingyul/cpnet#2]

**Comment by xingyul** [comment]
Did you set up cuDNN correctly?

**Comment by bignwei1029** [comment]
yes,  I install  cuda version is 9.0, cuDNN is  7

**Comment by xingyul** [comment]
Did you set the `arch` in Makefiles to be correct value? It also might be because of insufficient GPU memory.

**Comment by xingyul** [comment]
Solved in [here](https://github.com/xingyul/cpnet/issues/3).
