### ISSUE TITLE
run  the file train.py,  Line 373 appear the error : Segmentation fault

### ISSUE THREAD

**Issue by bignwei1029** [xingyul/cpnet#3]

**Comment by xingyul** [comment]
It seems that the memory of your computer is not enough. `train.py` needs a lot of memory. Depending on your batch size, it may need 64GB.

**Comment by bignwei1029** [comment]
my device is Tesla K40, it has 8  gpu，the memory of eyery gpu is 11.17GB.
I set gpu 0,1,2,3 ,  batch_size is  8, others parameters are same with you ,  run train.py , appear the error: 
(1)The following variables are in the dict, but not found in the graph: linear/b:0, linear/weights:0  (in dict_restore.py )
(2) Segmentation fault (in train.py  Line 373 )

**Comment by xingyul** [comment]
For memory of 64GB, I mean CPU memory. Also, it's recommended that you use 16GB-memory GPUs. Otherwise, the batch size has to be small and may generate different results.

**Comment by bignwei1029** [comment]
Bacause  my device is Tesla K40,  I change arch to sm_35,  it can run successfully. Thank you very much.
