### ISSUE TITLE
About training time？

### ISSUE THREAD

**Issue by FloydEdwin** [xingyul/cpnet#7]
Hello：
    I want to know how long  did the training sthv2 take?
 And i want to know why transform the webm->.gmeta&.gulp.why not using video-> image?
Thanks.

**Comment by xingyul** [comment]
Hi, thanks for your question. It depends on the computing resource you have. The training time should be less than Non-local Net.
The reason we transform webm to gulp instead of images is to reduce the time of reading from disk. Randomly accessing images takes long and gulp stores images into one file.

**Comment by FloydEdwin** [comment]
hello！
Thanks for your reply! I'm interested in your project. The point cloud idea is really great! Today, I try to transform your **CP module** into pytorch. Here I meet a problem.

def cp_module() function in net_utils.py 
I find :
    if distance == 'l2':
        import knn_l2 as knn which call **knn_op.so**

however i also find a function:
 def knn_l2(net, k, u)
**My question is are they equivalent?**
Thank you!

**Comment by xingyul** [comment]
Thanks for your interest. They should be equivalent. I didn't use the python version in my experiments but only the customized Tensorflow Op.

**Comment by FloydEdwin** [comment]
> Thanks for your interest. They should be equivalent. I didn't use the python version in my experiments but only the customized Tensorflow Op.

Hello. I think I have finished a CP moudle（pytorch version）.Thanks for your help. However , I also running your cpnet(tensorflow) code,.Here is some questions i need your help?
1.I find the default batch_size=32 for 4 GPUs. Unfortunately, on my own machine(**4 * 2080Ti 11 G**), I can only set batch=8 (batch_size=2 per GPU, It takes up about **7.2G/11G** of memory).As your paper described, the backbone is **ResNet34**, not a larger network, and input 12 frames per video. Is that cp moudle take up larger memory? if I set batch=3 per GPU, it will out of memory.An interesting detail is that your did't use resnet 50 or 101 in sthv2. Why not get better results on deeper networks?Is it memory or something else?
2.The default epoch is **251**? is that True? In fact ,Seldom have I seen such a long training period! Because of my batch can only set to **8** , I estimate it will take at least 40 days for training.I want to know how long did the training sthv2 take? and what type of gpu are you using?
3. I find your model switch 2D to 3D with **Temporal stride==1**,  such as 3x3 ----> 1x3x3, so that we can input multiple frames of a video not need to reshape the tensor.Do I understand that right?

I'm sorry to bother you again .But I'm really interested in your project.A little wish of mine is to reimplement your cpnet into pytorch.So all the details are important for me.
Thank you! Looking forward to your early reply.

**Comment by xingyul** [comment]
Thanks for your interest. 
1. The majority of my large experiments are trained on P100 GPUs, which have 16GB memory each. If I remember correctly, Res34 experiments can also be run on 4 GPUs with 12GB memory each. CP module takes some memory, but it shouldn't be the majority. Note the k-NN indexing step doesn't generate backward gradients. I didn't use deeper networks for something-something v2, because at the time of our CVPR submission, we are already the SOTA, so no need for larger models.
2. In practice, I stop training at around 80-100 epochs. Because after then, the learning rate will be clipped and stay the same. So no need to train any longer. Thanks for bringing that up and I'll change the default number of epochs to clear the confusion.
3. I'm not sure what you mean by "temporal stride". I think stride in temporal dimension is always 1. It's simply the argument passed to tf.nn.conv3d.

**Comment by FloydEdwin** [comment]
> Thanks for your interest.
> 
> 1. The majority of my large experiments are trained on P100 GPUs, which have 16GB memory each. If I remember correctly, Res34 experiments can also be run on 4 GPUs with 12GB memory each. CP module takes some memory, but it shouldn't be the majority. Note the k-NN indexing step doesn't generate backward gradients. I didn't use deeper networks for something-something v2, because at the time of our CVPR submission, we are already the SOTA, so no need for larger models.
> 2. In practice, I stop training at around 80-100 epochs. Because after then, the learning rate will be clipped and stay the same. So no need to train any longer. Thanks for bringing that up and I'll change the default number of epochs to clear the confusion.
> 3. I'm not sure what you mean by "temporal stride". I think stride in temporal dimension is always 1. It's simply the argument passed to tf.nn.conv3d.

Thank you very much for your patient reply to my questions. Your answers are of great help to me.
For problem three last time, Your understanding is correct.A 3D conv with temporal stride=1 is equal to conv2D. So stride in temporal dimension is always 1. I follow your code to inflated the pretrained imageNet weight to 3D which did a good  initialization.
Today I run my  C2D ResNet-34 baseline on sthv2. In paper, I found the following details described:

```
We trained two different CPNet models with ResNet-18
and -34 C2D as backbone respectively. We applied **two
phases of training** where we increase the number of frames
in a clip **from 12 to 24**. We freeze batch normalization
layers in the second phase. **The clip length are kept to
be 2s** 1. During inference, we use 6-crop spatially fullyconvolutional inference. We **sample 16 clips** evenly in temporal dimension from a full-length video and compute the
averaged softmax scores over 6 × 16 clips. The results are
listed in Table 5(a).
```
I have three questions:
1.how the two phares of training?  In the code you released, It seems that  i have not found the corresponding module. Of course, I didn't find it at ReadMe.So Can you describe the training process in detail?How many epochs  does it take to get to the second stage?
2.During inference, I find 6x16clips .However I found follows:
```
elif FCN == 6:
    loader_bsize = 8

```
So the real number is 8 not 16?
In fact the average frames of video(sthv2) is about 40~50, sample 16 clips may not a good choices.
3.The Visualization of **Figure 5** is really pretty! If you'd like, can you tell me what tools(maybe only python) you use for visualization?I've been doing a correspondence job.

Always asking you a lot of questions!
Thank you! Looking forward to your early reply.
Best wishes!
